go get -u github.com/gin-gonic/gin
go get -u github.com/gin-gonic/contrib/static
go get -u github.com/jinzhu/gorm
go get -u github.com/go-sql-driver/mysql
go get -u github.com/sirupsen/logrus
go get -u github.com/dgrijalva/jwt-go
go get -u github.com/tomazk/envcfg
go get -u golang.org/x/crypto/bcrypt
go get -u github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql
